server:
  port: 8080
    
spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/pantry?serverTimezone=UTC
    username: pantry
    password: pantry
    driverClassName: com.mysql.cj.jdbc.Driver
    
    
    
    