server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/provider
    username: provider
    password: provider
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/