server:
    port: 8081
  
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/provider
        username: provider
        password: provider
    jpa:
        hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/