server:
  port: 8080
  
eureka:
  instance:
    hostname: task
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
 
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/task?serverTimezone=UTC
    username: task
    password: task
    driverClassName: com.mysql.cj.jdbc.Driver
    
    
    
    