server:
  port: 8080
  
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
spring:
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/task?serverTimezone=UTC
    username: task
    password: task
    driverClassName: com.mysql.cj.jdbc.Driver
    
    
    
    